### ISSUE TITLE
Unable to build app

### ISSUE THREAD

**Issue by Om4n3k** [android-js/androidjs#116]
Hi!
After I inited a new project with androidjs init, i tried to build it with "androidjs build" and "androidjs build -f". Each time I'm getting this error:

```
Using SDK: 2.0.8
Building Apk ...
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'C:\\Users\\omank\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\build_tools\\apktool.jar',
    'b',
    'C:\\Users\\omank\\.androidjs\\cache\\androidjs-sdk',
    '-o',
    'C:\\Users\\omank\\.androidjs\\cache\\initial.apk',
    '--frame-path',
    'C:\\Users\\omank\\.androidjs\\cache'
  ]
}
```

OS: Win 10

Am I missing something? Thanks for help :)

**Comment by Chhekur** [comment]
you don't have java installed on your system.
please install jdk > 1.8

join [slack channel](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ) for support and discussion

**Comment by RGBrewer** [comment]
^ bump ... it doesnt mention anywhere that we need to do this
