### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by 1Map** [android-js/androidjs#126]
Unable to build - Keep on failing with
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip

androidjs b -f
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
failed to download, retrying..
re-trying
failed to download, retrying..
re-trying
failed to download, retrying..
re-trying

**Comment by Chhekur** [comment]
Do you have active and stable internet connection?

**Comment by RFlintstone** [comment]
> Do you have active and stable internet connection?

I have a stable internet connection and I have pretty much the same problem. 

```
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
C:\Users\rwfli\AppData\Roaming\npm\node_modules\androidjs-builder\src\modules\Html\ProgressBar.js:35
        process.stdout.clearLine();
                       ^

TypeError: process.stdout.clearLine is not a function
    at LoadingBar.clear (C:\Users\rwfli\AppData\Roaming\npm\node_modules\androidjs-builder\src\modules\Html\ProgressBar.js:35:24)
    at LoadingBar.next (C:\Users\rwfli\AppData\Roaming\npm\node_modules\androidjs-builder\src\modules\Html\ProgressBar.js:23:14)
    at Timeout._onTimeout (C:\Users\rwfli\AppData\Roaming\npm\node_modules\androidjs-builder\src\modules\Html\ProgressBar.js:42:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by BlackLight** [comment]
I'm experiencing the same issue here.

I can usually build without problems if I run the process manually from the command line:

```shell
$ npm install
$ androidjs build --release
```

However, I bump into the same issue reported above when I run the build process from an external script. In my case, I'm embedding the build script into the [F-Droid app build pipeline](https://gitlab.com/BlackLight1/fdroiddata/-/blob/master/metadata/tech.platypush.platypush.yml), and that's when I encounter the issue.

The reason in my case is that the `androidjs build` command is run from another process that does not have access to the terminal drawing primitives, therefore `clearLine` and `cursorTo` are not available.

I have put together a [very dirty fix](https://github.com/BlackLight/androidjs-builder/commit/e119cb187b6c106ddc337d2f534ebc56293495b8) in my fork (I don't feel like opening a proper pull request with this workaround) and in my F-Droid build script I have done some even dirtier tricks by `sed`-in the `dist` files to comment those lines.

However, this issue should definitely be tackled by the developers of AndroidJS. The build won't always be launched from a nice user terminal, and when it's launched from a script, a CI/CD pipeline or a Docker instance it will fail miserably. Please provide an option to at least skip the fancy on-terminal progress bar - even though my workarounds make things work the output of the process will still clutter the output log file.
