### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by ajuga2** [android-js/androidjs#128]
platform: raspberry pi 
installed node, androidjs and androidjs-builder

tc@keuken:~/myapp$ androidjs init
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /usr/local/lib/node_modules/androidjs-builder/src/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/androidjs-builder/src/bin.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/androidjs-builder/src/bin.js' ]
}
tc@keuken:~/myapp$

**Comment by DeveshPankaj** [comment]
We have fixed this issue.
You can take the latest version from npm -
``
$ npm install -g androidjs@2.1.9
``

**Comment by ajuga2** [comment]
tc@keuken:~/myapp$ npm install -g androidjs@2.1.9
npm ERR! code ETARGET
npm ERR! notarget No matching version found for androidjs@2.1.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tc/.npm/_logs/2020-08-06T15_37_59_250Z-debug.log
tc@keuken:~/myapp$

**Comment by Dhanya99** [comment]
check this
npm install -g androidjs-builder@2.1.9

**Comment by ajuga2** [comment]
One step further:

tc@keuken:~/myapp/sample-app-master/helloworld$ androidjs build
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
Data: 54924 KB : ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿█⣿⣿⣿⣿⣿⣿⣿⣿Killed

Gets killed (some kind of watchdog?).

**Comment by Chhekur** [comment]
Can you try again with 
```
$ androidjs update
```

**Comment by ajuga2** [comment]
Same (killed) by some watchdog. Perhaps a memory issue on raspberry pi. I have it running on windows, so i will close the issue
