### ISSUE TITLE
Error: spawn java ENOENT with androidjs build

### ISSUE THREAD

**Issue by ajuga2** [android-js/androidjs#129]
platform: windows 10
installed nodejs, androidjs and androidjs-builder
downloaded chat-app and trying to create apk:

C:\Users\Ajuga2\Desktop\chat-app>npm install
npm WARN myapp@1.0.0 No repository field.

audited 132 packages in 2s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Peter\Desktop\chat-app>androidjs build -f
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
Data: 55184 KB :██████████████████████████████████████████████████ √
copying assets ...
updating app name...
Setting app version ...
Version Code: 1
Version Name: 1.0
updating theme ...
theme attribute not found in package.json
Using SDK: 2.0.8
Building Apk ...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ajuga2** [comment]
Saw simalar problem with answer
