### ISSUE TITLE
Build/packaging error 

### ISSUE THREAD

**Issue by lukew3** [android-js/androidjs#145]
When I run `androidjs b` I get this output:
```
copying assets ...
updating app name...
Setting app version ...
Version Code: 1000032
Version Name: 1.0.0
updating theme ...
theme attribute not found in package.json
Using SDK: 2.1.0
Building Apk ...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
This happens both in the quick-start project and on my own. 

I'm using Ubuntu 20.04.1 LTS

**Comment by lukew3** [comment]
I was missing openjdk. Not an issue with the androidjs but a user error.
