### ISSUE TITLE
Fix build command so it can run in github actions

### ISSUE THREAD

**Issue by LPTP1Dev** [android-js/androidjs#161]
**Describe the bug**
Try to run build in github actions

**To Reproduce**
1. Set up installation and built in github actions

**Expected behavior**
Builds the app

**What happens**
 Error cause of console not running as admin:

Run androidjs build
--release= false
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:35
        process.stdout.clearLine();
                       ^

TypeError: process.stdout.clearLine is not a function
    at LoadingBar.clear (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:35:24)
    at LoadingBar.next (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:23:14)
    at Timeout._onTimeout (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:42:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Process completed with exit code 1.

**Comment by dydgns2017** [comment]
@LPTP1Dev 

Have you edited the android js build file?

First, there are two solutions

### one : use --force option when use build command

like thist

```
androidjs build --force
```

### two : 

i think u have to do reinstall android js builder 

```
npm uninstall -g androidjs-builder
npm i -g androidjs-builder
```

and then use command like this

```
androidjs update
androidjs build --force
```

**Comment by LPTP1Dev** [comment]
@dydgns2017

No I just installed it on github actions, find the action flow below:

- run: npm uninstall -g androidjs-builder 
- run: npm i androidjs
- run: npm i -g androidjs-builder
- run: androidjs build --force


(Some things like the uninstall and the --force I added after your message)

I'm still getting this error on the buuld command:

Run androidjs build --force
--release= false
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:35
        process.stdout.clearLine();
                       ^

TypeError: process.stdout.clearLine is not a function
    at LoadingBar.clear (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:35:24)
    at LoadingBar.next (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:23:14)
    at Timeout._onTimeout (/opt/hostedtoolcache/node/12.20.0/x64/lib/node_modules/androidjs-builder/modules/Html/ProgressBar.js:42:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Process completed with exit code 1.

**Comment by dydgns2017** [comment]
@LPTP1Dev 

have u try this ?

https://github.com/android-js/androidjs#quick-start

i think u not made android project file

see it this is helpful to u

https://android-js.github.io/docs/

**Comment by Chhekur** [comment]
@LPTP1Dev you are facing this problem because `process.stdout.clearLine` is not the part of debug consoles

**Comment by dydgns2017** [comment]
@LPTP1Dev 

i think its reference link is helpful to u
https://stackoverflow.com/a/58063715/11802642

so u should run into the window default console or fix to process.out function

**Comment by EhsanFox** [comment]
You are using the Git Bash i guess, just run cmd as administrator and you are done.
