### ISSUE TITLE
 process.stdout.clearLine is not a function

### ISSUE THREAD

**Issue by fdciabdul** [android-js/androidjs#194]
just following in this repo

```bash
npm install androidjs
npm install -g androidjs-builder
git clone https://github.com/android-js/sample-app
cd chat-app
npm install
androidjs b -f

```

but i can't build the app

so this is issue from readline package or from what ?

the outpur error when i try to run the command  `androidjs b -f`

```bash
--release= false
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
C:\Users\Administrator\AppData\Roaming\npm\node_modules\androidjs-builder\modules\Html\ProgressBar.js:35
        process.stdout.clearLine();
                       ^

TypeError: process.stdout.clearLine is not a function
    at LoadingBar.clear (C:\Users\Administrator\AppData\Roaming\npm\node_modules\androidjs-builder\modules\Html\ProgressBar.js:35:24)
    at LoadingBar.next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\androidjs-builder\modules\Html\ProgressBar.js:23:14)
    at Timeout._onTimeout (C:\Users\Administrator\AppData\Roaming\npm\node_modules\androidjs-builder\modules\Html\ProgressBar.js:42:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

```

**Comment by DeveshPankaj** [comment]
Which console application you are using? 
there may be some issue with non TTY (terminal) process.

- You can try using Power Shell

**Comment by fdciabdul** [comment]
thanks , now it's working with windows terminal
