### ISSUE TITLE
Cannot build story-app

### ISSUE THREAD

**Issue by jfbouzereau** [android-js/androidjs#44]
Hello,

I downloaded the sample apps from https://github.com/android-js/sample-app
When I try to build story-app, I get the following error:

webview: myapp
building
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
/usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
    at Request.<anonymous> (/usr/local/lib/node_modules/androidjs-builder/lib/native_app.js:125:27)
    at Request.emit (events.js:182:13)
    at reportState (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:83:21)
    at call (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:28:16)
    at Object.throttled [as reportState] (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:20:26)
    at onData (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:44:36)
    at IncomingMessage.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)

Any idea ? Thanks in advance

JFB

**Comment by Chhekur** [comment]
Try build command once again and you will good to go.
This error occurs when your internet slow or get the payload of size 0.

Thanks
Chhekur

**Comment by jfbouzereau** [comment]
Thanks for your quick reply. Worked on the fourth attempt :-(
By the way, is there any tool for uploading the apk to the smartphone ?

**Comment by Chhekur** [comment]
You can use ADB to install apk directly to your device via usb debugging

**Comment by jfbouzereau** [comment]
I though so, but I have to install Android SDK which is huge, and I tried androidjs precisely to avoid that ! Thanks anyway.

**Comment by Chhekur** [comment]
In order to install ADB you don't need to install android sdk, you can install that only ; )

**Comment by jfbouzereau** [comment]
Ok I downloaded the platform tools, only 30MB. The app is uploaded. Everything fine. Thanks !

**Comment by carylewis** [comment]
> Thanks for your quick reply. Worked on the fourth attempt :-(
> By the way, is there any tool for uploading the apk to the smartphone ?

I had to try 6 times? What is the exact issue? I would recommend adding a note to the docs - it took me quite a while to find this note.

**Comment by Chhekur** [comment]
> > Thanks for your quick reply. Worked on the fourth attempt :-(
> > By the way, is there any tool for uploading the apk to the smartphone ?
> 
> I had to try 6 times? What is the exact issue? I would recommend adding a note to the docs - it took me quite a while to find this note.

Actually we are writing the builder from scratch to fix all the existing problems ; )
