### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by interfaith** [android-js/androidjs#48]
**Describe the bug**
androidjs b -f
webview: myapp
building
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
    at Request.<anonymous> (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/lib/native_app.js:125:27)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at reportState (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:83:21)
    at call (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:28:16)
    at Object.throttled [as reportState] (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:20:26)
    at onData (/home/spowage/.nvm/versions/node/v8.11.4/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:44:36)
    at emitOne (events.js:121:20)
    at IncomingMessage.emit (events.js:211:7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chhekur** [comment]
Run build command again...

This error occcurs when your intermet connection is slow or builder get payload of length 0.
