### ISSUE TITLE
using chardet package

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs#51]
```sh
cool@zenbook:~/Documents/Projects/cool Parole$ npm i chardet

> nodemon@1.19.2 postinstall /home/cool/Documents/Projects/cool Parole/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN cool@5.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ chardet@0.8.0
added 314 packages from 190 contributors and audited 2508 packages in 5.683s
found 0 vulnerabilities




cool@zenbook:~/Documents/Projects/cool Parole$ androidjs b
Testing 'Theme Update' ...
webview: cool
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/cool/.androidjs/androidjs-sdk
removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/cool/Documents/Projects/cool Parole 
to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
[ '/home/cool/Documents/Projects/cool Parole/dist' ]
(node:16701) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/home/cool/Documents/Projects/cool Parole/node_modules/.bin/atob'
    at Object.readdirSync (fs.js:865:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:18)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
(node:16701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
㋛ using androidjs-sdk {"version":"2.0.0"}
cool@zenbook:~/Documents/Projects/cool Parole$ 


```

How can I solve this problem?

**Comment by Chhekur** [comment]
The problem is you are using a `npm package` which is hardware dependent so it won't gonna work on mobile platform.

**Comment by szhatef** [comment]
how can I use packages without using npm?

**Comment by Chhekur** [comment]
Use the packages from `npm` no problem, but don't use hardware dependent packages

**Comment by szhatef** [comment]
Do you know any equivalent package for "**request** Package" which can be run on Mobile Platform?

**Comment by Chhekur** [comment]
I think request module will work on android js

**Comment by Chhekur** [comment]
> ```shell
> cool@zenbook:~/Documents/Projects/cool Parole$ npm i chardet
> 
> > nodemon@1.19.2 postinstall /home/cool/Documents/Projects/cool Parole/node_modules/nodemon
> > node bin/postinstall || exit 0
> 
> npm WARN cool@5.0.2 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> + chardet@0.8.0
> added 314 packages from 190 contributors and audited 2508 packages in 5.683s
> found 0 vulnerabilities
> 
> 
> 
> 
> cool@zenbook:~/Documents/Projects/cool Parole$ androidjs b
> Testing 'Theme Update' ...
> webview: cool
> building
> updating...  [object Object]
> {
>   fullScreen: true,
>   colorAccent: '@color/colorAccent',
>   colorPrimary: '@color/colorPrimary',
>   colorPrimaryDark: '@color/colorPrimaryDark'
> }
> [
>   { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
>   { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
>   { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
>   { _: true, '$': { name: 'android:windowNoTitle' } },
>   { _: true, '$': { name: 'android:windowFullscreen' } },
>   { _: 'false', '$': { name: 'android:windowActionBar' } }
> ]
> Done!
> checking Core
> using core /home/cool/.androidjs/androidjs-sdk
> removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
> copying Assets
> copying from /home/cool/Documents/Projects/cool Parole 
> to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
> [ '/home/cool/Documents/Projects/cool Parole/dist' ]
> (node:16701) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/home/cool/Documents/Projects/cool Parole/node_modules/.bin/atob'
>     at Object.readdirSync (fs.js:865:3)
>     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:18)
>     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
>     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
>     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
>     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
>     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
>     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
>     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
>     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
> (node:16701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:16701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ㋛ using androidjs-sdk {"version":"2.0.0"}
> cool@zenbook:~/Documents/Projects/cool Parole$ 
> ```
> 
> How can I solve this problem?

We are trying to fix this bug, in order to make it work right now. You can delete all the folders they are starting with dot From node modules

**Comment by szhatef** [comment]
> > ```shell
> > cool@zenbook:~/Documents/Projects/cool Parole$ npm i chardet
> > 
> > > nodemon@1.19.2 postinstall /home/cool/Documents/Projects/cool Parole/node_modules/nodemon
> > > node bin/postinstall || exit 0
> > 
> > npm WARN cool@5.0.2 No repository field.
> > npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
> > npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> > 
> > + chardet@0.8.0
> > added 314 packages from 190 contributors and audited 2508 packages in 5.683s
> > found 0 vulnerabilities
> > 
> > 
> > 
> > 
> > cool@zenbook:~/Documents/Projects/cool Parole$ androidjs b
> > Testing 'Theme Update' ...
> > webview: cool
> > building
> > updating...  [object Object]
> > {
> >   fullScreen: true,
> >   colorAccent: '@color/colorAccent',
> >   colorPrimary: '@color/colorPrimary',
> >   colorPrimaryDark: '@color/colorPrimaryDark'
> > }
> > [
> >   { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
> >   { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
> >   { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
> >   { _: true, '$': { name: 'android:windowNoTitle' } },
> >   { _: true, '$': { name: 'android:windowFullscreen' } },
> >   { _: 'false', '$': { name: 'android:windowActionBar' } }
> > ]
> > Done!
> > checking Core
> > using core /home/cool/.androidjs/androidjs-sdk
> > removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
> > copying Assets
> > copying from /home/cool/Documents/Projects/cool Parole 
> > to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
> > [ '/home/cool/Documents/Projects/cool Parole/dist' ]
> > (node:16701) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/home/cool/Documents/Projects/cool Parole/node_modules/.bin/atob'
> >     at Object.readdirSync (fs.js:865:3)
> >     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:18)
> >     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
> >     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
> >     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
> >     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
> >     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
> >     at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
> >     at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
> >     at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
> > (node:16701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> > (node:16701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ㋛ using androidjs-sdk {"version":"2.0.0"}
> > cool@zenbook:~/Documents/Projects/cool Parole$ 
> > ```
> > 
> > 
> > How can I solve this problem?
> 
> We are trying to fix this bug, in order to make it work right now. You can delete all the folders they are starting with dot From node modules

there is just one such folder : dot-prop

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)
