### ISSUE TITLE
Could the "request Package" be used by AndroidJS

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs#52]
```sh

npm i request

> nodemon@1.19.2 postinstall /home/cool/Documents/Projects/cool Parole/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN cool@5.0.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ request@2.88.0
added 314 packages from 190 contributors and audited 2571 packages in 9.334s
found 0 vulnerabilities


cool@zenbook:~/Documents/Projects/cool Parole$ androidjs b
Testing 'Theme Update' ...
webview: cool
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/cool/.androidjs/androidjs-sdk
removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/cool/Documents/Projects/cool Parole 
to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
[ '/home/cool/Documents/Projects/cool Parole/dist' ]
(node:24509) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/home/cool/Documents/Projects/cool Parole/node_modules/.bin/atob'
    at Object.readdirSync (fs.js:865:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:69:18)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
    at listDirectorySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:70:3)
    at copydirSync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:44:7)
    at copyFromArraySync (/home/cool/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/copy-dir/libs/copydirSync.js:76:3)
(node:24509) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
㋛ using androidjs-sdk {"version":"2.0.0"}

```

**Comment by szhatef** [comment]
any Response?

**Comment by szhatef** [comment]
??
