### ISSUE TITLE
androidjs init fails

### ISSUE THREAD

**Issue by bengaid** [android-js/androidjs#79]
androidjs init command fails.

**To Reproduce**

Type :
```sh
androidjs init
```

**Error Log**
```sh
                     _           _     _        _  _____
     /\             | |         (_)   | |      | |/ ____|
    /  \   _ __   __| |_ __ ___  _  __| |      | | (___
   / /\ \ | '_ \ / _` | '__/ _ \| |/ _` |  _   | |\___ \
  / ____ \| | | | (_| | | | (_) | | (_| | | |__| |____) |
 /_/    \_\_| |_|\__,_|_|  \___/|_|\__,_|  \____/|_____/


? Application name: test
? Application name: test
? Project type: (Use arrow keys)
? Project type: HTML/CSS
Testing 'Theme Update' ...
Creating Native app at C:\Users\bengaid\androidjs
Downloading Sample Project From:
https://raw.githubusercontent.com/android-js/sample-app/master/vue-js-example
invalid github url
Failed to connect to GitHub
Check Your InterNet Connection



(node:9748) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/android-js/sample-app/git/trees/HEAD?recursive=1 failed, reason: connect ETIMEDOUT 140.82.118.5:443
    at ClientRequest.<anonymous> (C:\Users\bengaid\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:9748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9748) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/android-js/sample-app/git/trees/HEAD?recursive=1 failed, reason: connect ETIMEDOUT 140.82.118.5:443
    at ClientRequest.<anonymous> (C:\Users\bengaid\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:9748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Desktop**
 - OS: [Windows 7 SP1 64 bits]
 - Version [node.js 8.14.0]

**Comment by chongjh** [comment]
I think this is one you have to retry several times until it starts to download the SDK.

**Comment by Chhekur** [comment]
this is because of internet connection, actually you are not connected to internet.

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)
