### ISSUE TITLE
androidjs b fails

### ISSUE THREAD

**Issue by bengaid** [android-js/androidjs#80]
**Describe the bug**
androidjs b fails. See details below.

**To Reproduce**
```sh
androidjs init
```
then
```sh
androidjs b
```
command log:
```sh
Testing 'Theme Update' ...
webview: test
building
updating...  [object Object]
{ fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark' }
/usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40
                    let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined
    at /usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40:38
    at Parser.<anonymous> (/usr/lib/node_modules/androidjs-builder/node_modules/                                                                                                                                                                                               xml2js/lib/parser.js:308:18)
    at Parser.emit (events.js:198:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/androidjs                                                                                                                                                                                               -builder/node_modules/xml2js/lib/parser.js:327:16)
    at Parser.parseString (/usr/lib/node_modules/androidjs-builder/node_modules/                                                                                                                                                                                               xml2js/lib/parser.js:5:59)
    at ReadFileContext.callback (/usr/lib/node_modules/androidjs-builder/lib/upd                                                                                                                                                                                               ate_theme.js:36:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
```

**Desktop (please complete the following information):**
 - OS: [Debian stretch]

**Comment by chongjh** [comment]
I'm getting the same problem but it was fine a few days ago. 

- OS: Ubuntu 19.10

**Comment by Romans96** [comment]
The same for me, and i can't update (androidjs update doesn't work)

**Comment by carylewis** [comment]
I am experiencing the same issue.

There was another issue that mentioned having to download androidjs-sdk, but where should that be downloaded to? Inside the project directory?

**Comment by Chhekur** [comment]
> I am experiencing the same issue.
> 
> There was another issue that mentioned having to download androidjs-sdk, but where should that be downloaded to? Inside the project directory?

It automatically downloads the `SDK` at location location, doesn't matter where you run command from.

**Comment by yanickrochon** [comment]
Getting the same issue, Though it seems to be related to androidjs-builder....

**Comment by Chhekur** [comment]
> Getting the same issue, Though it seems to be related to androidjs-builder....

Most of the users have faced this problem in windows, we are actually implementing `androidjs-builder` from scratch which will fix most of the existing problem and will available soon ; )

**Comment by yanickrochon** [comment]
> Most of the users have faced this problem in windows, we are actually implementing `androidjs-builder` from scratch which will fix most of the existing problem and will available soon ; )

Perhaps, but I do not have Windows. :)

**Comment by PiR1** [comment]
I'm getting the same problem on Ubuntu 18.04.

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )

**Comment by PiR1** [comment]
It works for me, thanks.

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)
